version: '3.8'

services:
  mysql:
    image: mysql:latest
    build: 
      context: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=SEP
      - MYSQL_DATABASE=root
      - MYSQL_DATABASE=SEP
    ports:
      - "3307:3306"
    restart: always
    
  backend:
    build: ./Backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/SEP
    depends_on:
      - mysql
    restart: always

  frontend:
    build: ./Frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: always